#!/bin/sh

# This uses gox from https://github.com/mitchellh/gox
# Make sure you've run gox -build-toolchain

rm -rf build

gox -output "build/{{.OS}}/{{.Arch}}/{{.Dir}}"

cat <<'#EOF' > build/README.txt
This directory contains builds of the rclone program.

Rclone is a program to transfer files to and from cloud storage
systems such as Google Drive, Amazon S3 and Swift (Rackspace
Cloudfiles).

See the project website here: https://github.com/ncw/rclone for more
details.

The files in this directory are organised by OS and processor type

#EOF

mv build/darwin build/osx

( cd build ; tree . >> README.txt )
