#!/bin/sh

set -e

# This uses gox from https://github.com/mitchellh/gox
# Make sure you've run gox -build-toolchain

if [ "$1" == "" ]; then
    echo "Syntax: $0 Version"
    exit 1
fi
VERSION="$1"

rm -rf build

gox -output "build/{{.Dir}}-${VERSION}-{{.OS}}-{{.Arch}}/{{.Dir}}"

mv build/rclone-${VERSION}-darwin-amd64 build/rclone-${VERSION}-osx-amd64
mv build/rclone-${VERSION}-darwin-386 build/rclone-${VERSION}-osx-386

cd build

for d in `ls`; do
    cp -a ../MANUAL.txt $d/README.txt
    cp -a ../MANUAL.html $d/README.html
    cp -a ../rclone.1 $d/
    zip -r9 $d.zip $d
    rm -rf $d
done

cd ..
