{
  "version": "v1",
  "baseUrl": "https://script.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.google.com/m8/feeds": {
          "description": "Manage your contacts"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "Manage your calendars"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "View and manage the files in your Google Drive"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "View and manage your spreadsheets in Google Drive"
        },
        "https://mail.google.com/": {
          "description": "Read, send, delete, and manage your email"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "description": "An API for managing and executing Google Apps Script projects.",
  "servicePath": "",
  "rootUrl": "https://script.googleapis.com/",
  "basePath": "",
  "ownerDomain": "google.com",
  "name": "script",
  "batchPath": "batch",
  "id": "script:v1",
  "documentationLink": "https://developers.google.com/apps-script/api",
  "revision": "20180110",
  "fullyEncodeReservedExpansion": true,
  "title": "Google Apps Script API",
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "resources": {
    "scripts": {
      "methods": {
        "run": {
          "flatPath": "v1/scripts/{scriptId}:run",
          "path": "v1/scripts/{scriptId}:run",
          "id": "script.scripts.run",
          "description": "Runs a function in an Apps Script project. The project must be deployed\nfor use with the Apps Script API.\n\nThis method requires authorization with an OAuth 2.0 token that includes at\nleast one of the scopes listed in the [Authorization](#authorization)\nsection; script projects that do not require authorization cannot be\nexecuted through this API. To find the correct scopes to include in the\nauthentication token, open the project in the script editor, then select\[...]",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ]
        }
      }
    },
    "projects": {
      "resources": {
        "deployments": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.get",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Gets a deployment of an Apps Script project."
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "path": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.list",
              "description": "Lists the deployments of an Apps Script project."
            },
            "update": {
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.update",
              "description": "Updates a deployment of an Apps Script project.",
              "httpMethod": "PUT"
            },
            "create": {
              "description": "Creates a deployment of an Apps Script project.",
              "httpMethod": "POST",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "path": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.create"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.delete",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Deletes a deployment of an Apps Script project."
            }
          }
        },
        "versions": {
          "methods": {
            "get": {
              "description": "Gets a version of a script project.",
              "httpMethod": "GET",
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "id": "script.projects.versions.get",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}"
            },
            "list": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.list",
              "path": "v1/projects/{scriptId}/versions",
              "description": "List the versions of a script project.",
              "httpMethod": "GET"
            },
            "create": {
              "description": "Creates a new immutable version using the current code, with a unique\nversion number.",
              "httpMethod": "POST",
              "flatPath": "v1/projects/{scriptId}/versions",
              "path": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.create"
            }
          }
        }
      },
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1/projects/{scriptId}",
          "id": "script.projects.get",
          "path": "v1/projects/{scriptId}",
          "description": "Gets a script project's metadata."
        },
        "updateContent": {
          "description": "Updates the content of the specified script project.\nThis content is stored as the HEAD version, and is used when the script is\nexecuted as a trigger, in the script editor, in add-on preview mode, or as\na web app or Apps Script API in development mode. This clears all the\nexisting files in the project.",
          "httpMethod": "PUT",
          "flatPath": "v1/projects/{scriptId}/content",
          "path": "v1/projects/{scriptId}/content",
          "id": "script.projects.updateContent"
        },
        "create": {
          "path": "v1/projects",
          "id": "script.projects.create",
          "description": "Creates a new, empty script project with no script files and a base\nmanifest file.",
          "httpMethod": "POST",
          "flatPath": "v1/projects"
        },
        "getContent": {
          "flatPath": "v1/projects/{scriptId}/content",
          "id": "script.projects.getContent",
          "path": "v1/projects/{scriptId}/content",
          "description": "Gets the content of the script project, including the code source and\nmetadata for each script file.",
          "httpMethod": "GET"
        },
        "getMetrics": {
          "httpMethod": "GET",
          "flatPath": "v1/projects/{scriptId}/metrics",
          "path": "v1/projects/{scriptId}/metrics",
          "id": "script.projects.getMetrics",
          "description": "Get metrics data for scripts, such as number of executions and\nactive users."
        }
      }
    },
    "processes": {
      "methods": {
        "listScriptProcesses": {
          "description": "List information about a script's executed processes, such as process type\nand current status.",
          "httpMethod": "GET",
          "flatPath": "v1/processes:listScriptProcesses",
          "id": "script.processes.listScriptProcesses",
          "path": "v1/processes:listScriptProcesses"
        },
        "list": {
          "path": "v1/processes",
          "id": "script.processes.list",
          "description": "List information about processes made by or on behalf of a user,\nsuch as process type and current status.",
          "httpMethod": "GET",
          "flatPath": "v1/processes"
        }
      }
    }
  },
  "protocol": "rest"
}
