{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/photoslibrary": {
          "description": "View and manage your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.appendonly": {
          "description": "Add to your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.readonly": {
          "description": "View your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata": {
          "description": "Manage photos added by this app"
        },
        "https://www.googleapis.com/auth/photoslibrary.sharing": {
          "description": "Manage and add to shared albums on your behalf"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://photoslibrary.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Photos Library",
  "description": "Manage photos, videos, and albums in Google Photos\n",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/photos/",
  "fullyEncodeReservedExpansion": true,
  "id": "photoslibrary:v1",
  "kind": "discovery#restDescription",
  "name": "photoslibrary",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "albums": {
      "methods": {
        "addEnrichment": {
          "description": "Adds an enrichment to a specified position in a defined album.",
          "flatPath": "v1/albums/{albumsId}:addEnrichment",
          "httpMethod": "POST",
          "id": "photoslibrary.albums.addEnrichment",
          "path": "v1/albums/{+albumId}:addEnrichment",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        },
        "create": {
          "description": "Creates an album in a user's Google Photos library.",
          "flatPath": "v1/albums",
          "httpMethod": "POST",
          "id": "photoslibrary.albums.create",
          "path": "v1/albums",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        },
        "get": {
          "description": "Returns the album specified by the given album id.",
          "flatPath": "v1/albums/{albumsId}",
          "httpMethod": "GET",
          "id": "photoslibrary.albums.get",
          "path": "v1/albums/{+albumId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ]
        },
        "list": {
          "description": "Lists all albums shown to a user in the 'Albums' tab of the Google\nPhotos app.",
          "flatPath": "v1/albums",
          "httpMethod": "GET",
          "id": "photoslibrary.albums.list",
          "path": "v1/albums",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ]
        },
        "share": {
          "description": "Marks an album as 'shared' and accessible to other users. This action can\nonly be performed on albums which were created by the developer via the\nAPI.",
          "flatPath": "v1/albums/{albumsId}:share",
          "httpMethod": "POST",
          "id": "photoslibrary.albums.share",
          "path": "v1/albums/{+albumId}:share",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        }
      }
    },
    "mediaItems": {
      "methods": {
        "batchCreate": {
          "description": "Creates one or more media items in a user's Google Photos library.\nIf an album id is specified, the media item(s) are also added to the album.\nBy default the media item(s) will be added to the end of the library or\nalbum.\n\nIf an album id and position are both defined, then the media items will\nbe added to the album at the specified position.\n\nIf multiple media items are given, they will be inserted at the specified\nposition.",
          "flatPath": "v1/mediaItems:batchCreate",
          "httpMethod": "POST",
          "id": "photoslibrary.mediaItems.batchCreate",
          "path": "v1/mediaItems:batchCreate",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        },
        "get": {
          "description": "Returns the media item specified based on a given media item id.",
          "flatPath": "v1/mediaItems/{mediaItemsId}",
          "httpMethod": "GET",
          "id": "photoslibrary.mediaItems.get",
          "path": "v1/mediaItems/{+mediaItemId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ]
        },
        "search": {
          "description": "Searches for media items in a user's Google Photos library.\nIf no filters are set, then all media items in the user's library will be\nreturned.\n\nIf an album is set, all media items in the specified album will be\nreturned.\n\nIf filters are specified, anything that matches the filters from the user's\nlibrary will be listed.\n\nIf an album and filters are set, then this will result in an error.",
          "flatPath": "v1/mediaItems:search",
          "httpMethod": "POST",
          "id": "photoslibrary.mediaItems.search",
          "path": "v1/mediaItems:search",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ]
        }
      }
    },
    "sharedAlbums": {
      "methods": {
        "join": {
          "description": "Joins a shared album on behalf of the Google Photos user.",
          "flatPath": "v1/sharedAlbums:join",
          "httpMethod": "POST",
          "id": "photoslibrary.sharedAlbums.join",
          "path": "v1/sharedAlbums:join",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        },
        "list": {
          "description": "Lists all shared albums shown to a user in the 'Sharing' tab of the\nGoogle Photos app.",
          "flatPath": "v1/sharedAlbums",
          "httpMethod": "GET",
          "id": "photoslibrary.sharedAlbums.list",
          "path": "v1/sharedAlbums",
          "scopes": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ]
        }
      }
    }
  },
  "revision": "20180508",
  "rootUrl": "https://photoslibrary.googleapis.com/",
  "servicePath": "",
  "title": "Photos Library API",
  "version": "v1",
  "version_module": true
}