// Package metadata provides types and utilities for YTFS metadata caching
package metadata

import (
	"time"
)

// CacheConfig represents the global cache configuration
type CacheConfig struct {
	Version  string `json:"version"`
	CacheDir string `json:"cacheDir"`

	TTL struct {
		VideoMetadata int `json:"videoMetadata"` // Seconds
		Thumbnails    int `json:"thumbnails"`    // Seconds
		Subtitles     int `json:"subtitles"`     // Seconds
		Chapters      int `json:"chapters"`      // Seconds
		ChannelInfo   int `json:"channelInfo"`   // Seconds
		PlaylistInfo  int `json:"playlistInfo"`  // Seconds
	} `json:"ttl"`

	ThumbnailQuality struct {
		Default       string `json:"default"`       // "medium" or "high"
		MaxResolution bool   `json:"maxResolution"` // Download maxresdefault
	} `json:"thumbnailQuality"`

	Subtitles struct {
		AutoGenerated      bool     `json:"autoGenerated"`
		PreferredLanguages []string `json:"preferredLanguages"`
		MaxLanguages       int      `json:"maxLanguages"`
	} `json:"subtitles"`

	Chapters struct {
		Enabled     bool   `json:"enabled"`
		CacheFormat string `json:"cacheFormat"` // "xml" or "json"
	} `json:"chapters"`

	CleanupPolicy struct {
		Enabled      bool  `json:"enabled"`
		CleanupAge   int   `json:"cleanupAge"`   // Seconds
		MaxCacheSize int64 `json:"maxCacheSize"` // Bytes
	} `json:"cleanupPolicy"`
}

// VideoMetadata represents cached video information
type VideoMetadata struct {
	ID            string   `json:"id"`
	Title         string   `json:"title"`
	Description   string   `json:"description"`
	Duration      int      `json:"duration"` // Seconds
	UploadDate    string   `json:"upload_date"`
	Uploader      string   `json:"uploader"`
	UploaderID    string   `json:"uploader_id"`
	UploaderURL   string   `json:"uploader_url"`
	ViewCount     int64    `json:"view_count"`
	LikeCount     int64    `json:"like_count"`
	CommentCount  int64    `json:"comment_count"`
	AgeRestricted bool     `json:"age_restricted"`
	Categories    []string `json:"categories"`
	Tags          []string `json:"tags"`
	Thumbnail     string   `json:"thumbnail"`
	WebpageURL    string   `json:"webpage_url"`

	// Media info
	Ext        string `json:"ext"`
	VCodec     string `json:"vcodec"`
	ACodec     string `json:"acodec"`
	FPS        int    `json:"fps"`
	Resolution string `json:"resolution"`

	// yt-dlp fetch timestamp
	FetchTimestamp int64 `json:"_ytdl_fetch_timestamp"`
}

// NFOMovie represents the Emby NFO XML structure (as Go struct for marshaling)
type NFOMovie struct {
	XMLName string `xml:"movie"`

	// Identification
	Title         string     `xml:"title"`
	OriginalTitle string     `xml:"originaltitle"`
	SortTitle     string     `xml:"sorttitle"`
	UniqueIDs     []UniqueID `xml:"uniqueid"`

	// Core metadata
	Plot    string `xml:"plot"`
	Tagline string `xml:"tagline"`
	Runtime int    `xml:"runtime"`

	// Dates
	Aired     string `xml:"aired"`
	Year      int    `xml:"year"`
	DateAdded string `xml:"dateadded"`

	// People
	Actors   []Actor `xml:"actor"`
	Director string  `xml:"director"`

	// Content classification
	ContentRating string `xml:"contentrating"`
	Rating        Rating `xml:"rating"`

	// Genres and tags
	Genres []string `xml:"genre"`
	Tags   []string `xml:"tag"`

	// Engagement metrics
	Likes    int64 `xml:"likes"`
	Views    int64 `xml:"views"`
	Comments int64 `xml:"comments"`

	// Media & links
	Thumbs  []Thumb  `xml:"thumb"`
	Fanarts []Fanart `xml:"fanart"`
	URL     string   `xml:"url"`

	// Optional: Chapters
	Chapters []Chapter `xml:"chapters>chapter"`

	// Optional: Credits
	Credits Credits `xml:"credits"`
}

// UniqueID represents a unique identifier in NFO
type UniqueID struct {
	Type  string `xml:"type,attr"`
	Value string `xml:",chardata"`
}

// Actor represents a person in NFO
type Actor struct {
	Name  string `xml:"name"`
	Role  string `xml:"role"`
	Thumb string `xml:"thumb"`
}

// Rating represents a rating value in NFO
type Rating struct {
	Default bool    `xml:"default,attr"`
	Value   float32 `xml:",chardata"`
}

// Thumb represents a thumbnail/poster in NFO
type Thumb struct {
	Type    string `xml:"type,attr"`
	Aspect  string `xml:"aspect,attr"`
	Preview string `xml:"preview,attr"`
	URL     string `xml:",chardata"`
}

// Fanart represents fanart images in NFO
type Fanart struct {
	Thumbs []FanartThumb `xml:"thumb"`
}

// FanartThumb represents a fanart thumbnail
type FanartThumb struct {
	URL string `xml:"url,attr"`
}

// Chapter represents a chapter marker in NFO
type Chapter struct {
	Name     string `xml:"name"`
	Position int    `xml:"position"`
}

// Credits represents credits section in NFO
type Credits struct {
	Editor string `xml:"editor"`
}

// ThumbnailManifest tracks cached thumbnail files and their metadata
type ThumbnailManifest struct {
	VideoID      string                       `json:"videoId"`
	Downloaded   time.Time                    `json:"downloaded"`
	ExpiresAt    time.Time                    `json:"expiresAt"`
	Sizes        map[string]ThumbnailFileInfo `json:"sizes"`
	PrimaryThumb string                       `json:"primaryThumb"`
}

// ThumbnailFileInfo describes a cached thumbnail file
type ThumbnailFileInfo struct {
	URL      string `json:"url"`
	Width    int    `json:"width"`
	Height   int    `json:"height"`
	Cached   bool   `json:"cached"`
	Filename string `json:"filename"`
}

// SubtitlesManifest tracks cached subtitle files
type SubtitlesManifest struct {
	VideoID     string                  `json:"videoId"`
	LastFetched time.Time               `json:"lastFetched"`
	ExpiresAt   time.Time               `json:"expiresAt"`
	Subtitles   map[string]SubtitleInfo `json:"subtitles"`
}

// SubtitleInfo describes a cached subtitle file
type SubtitleInfo struct {
	Name          string `json:"name"`
	AutoGenerated bool   `json:"auto_generated"`
	Cached        bool   `json:"cached"`
	Filename      string `json:"filename"`
}

// ChapterMarker represents a single chapter
type ChapterMarker struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	StartMs int    `json:"startMs"`
	EndMs   int    `json:"endMs"`
}

// ChaptersManifest represents parsed chapters for a video
type ChaptersManifest struct {
	VideoID  string          `json:"videoId"`
	Chapters []ChapterMarker `json:"chapters"`
	Format   string          `json:"format"` // "xml" or "json"
}

// ExpiryTracker tracks expiry times for cached items
type ExpiryTracker struct {
	Metadata  ExpiryEntry `json:"metadata"`
	Thumbnail ExpiryEntry `json:"thumbnail"`
	Subtitles ExpiryEntry `json:"subtitles"`
	Chapters  ExpiryEntry `json:"chapters"`
}

// ExpiryEntry represents expiry information for a cache item
type ExpiryEntry struct {
	CreatedAt  time.Time `json:"createdAt"`
	ExpiresAt  time.Time `json:"expiresAt"`
	TTLSeconds int       `json:"ttlSeconds"`
}

// ChannelMetadata represents cached channel information
type ChannelMetadata struct {
	ID                   string `json:"id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SubscriberCount      int64  `json:"subscriber_count"`
	ChannelFollowerCount int64  `json:"channel_follower_count"`
	ThumbnailURL         string `json:"thumbnail_url"`
	BannerURL            string `json:"banner_url"`
	ChannelURL           string `json:"channel_url"`
	FetchTimestamp       int64  `json:"_ytdl_fetch_timestamp"`
}

// PlaylistMetadata represents cached playlist information
type PlaylistMetadata struct {
	ID             string `json:"id"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	PlaylistCount  int    `json:"playlist_count"`
	URL            string `json:"url"`
	ThumbnailURL   string `json:"thumbnail_url"`
	FetchTimestamp int64  `json:"_ytdl_fetch_timestamp"`
}

// CacheStats represents statistics about cache usage
type CacheStats struct {
	TotalSize       int64
	TotalFiles      int
	VideosCount     int
	ThumbnailsCount int
	SubtitlesCount  int
	ChaptersCount   int
	ChannelsCount   int
	PlaylistsCount  int
	OldestFile      time.Time
	NewestFile      time.Time
}
