{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/taskqueue": {
          "description": "Manage your Tasks and Taskqueues"
        },
        "https://www.googleapis.com/auth/taskqueue.consumer": {
          "description": "Consume Tasks from your Taskqueues"
        }
      }
    }
  },
  "basePath": "/taskqueue/v1beta1/projects/",
  "baseUrl": "https://www.googleapis.com/taskqueue/v1beta1/projects/",
  "batchPath": "batch/taskqueue/v1beta1",
  "description": "Accesses a Google App Engine Pull Task Queue over REST.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/appengine/docs/python/taskqueue/rest",
  "etag": "\"-iA1DTNe4s-I6JZXPt1t1Ypy8IU/UNHEtVyVE-POJmRW0SrDcBQE6KY\"",
  "id": "taskqueue:v1beta1",
  "kind": "discovery#restDescription",
  "name": "taskqueue",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "taskqueues": {
      "methods": {
        "get": {
          "description": "Get detailed information about a TaskQueue.",
          "httpMethod": "GET",
          "id": "taskqueue.taskqueues.get",
          "path": "{project}/taskqueues/{taskqueue}",
          "scopes": [
            "https://www.googleapis.com/auth/taskqueue",
            "https://www.googleapis.com/auth/taskqueue.consumer"
          ]
        }
      }
    },
    "tasks": {
      "methods": {
        "delete": {
          "description": "Delete a task from a TaskQueue.",
          "httpMethod": "DELETE",
          "id": "taskqueue.tasks.delete",
          "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/taskqueue",
            "https://www.googleapis.com/auth/taskqueue.consumer"
          ]
        },
        "get": {
          "description": "Get a particular task from a TaskQueue.",
          "httpMethod": "GET",
          "id": "taskqueue.tasks.get",
          "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
          "scopes": [
            "https://www.googleapis.com/auth/taskqueue",
            "https://www.googleapis.com/auth/taskqueue.consumer"
          ]
        },
        "lease": {
          "description": "Lease 1 or more tasks from a TaskQueue.",
          "httpMethod": "POST",
          "id": "taskqueue.tasks.lease",
          "path": "{project}/taskqueues/{taskqueue}/tasks/lease",
          "scopes": [
            "https://www.googleapis.com/auth/taskqueue",
            "https://www.googleapis.com/auth/taskqueue.consumer"
          ]
        },
        "list": {
          "description": "List Tasks in a TaskQueue",
          "httpMethod": "GET",
          "id": "taskqueue.tasks.list",
          "path": "{project}/taskqueues/{taskqueue}/tasks",
          "scopes": [
            "https://www.googleapis.com/auth/taskqueue",
            "https://www.googleapis.com/auth/taskqueue.consumer"
          ]
        }
      }
    }
  },
  "revision": "20160428",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "taskqueue/v1beta1/projects/",
  "title": "TaskQueue API",
  "version": "v1beta1"
}