// Code generated by "stringer -type=LogLevel"; DO NOT EDIT

package fs

import "fmt"

const _LogLevel_name = "LogLevelEmergencyLogLevelAlertLogLevelCriticalLogLevelErrorLogLevelWarningLogLevelNoticeLogLevelInfoLogLevelDebug"

var _LogLevel_index = [...]uint8{0, 17, 30, 46, 59, 74, 88, 100, 113}

func (i LogLevel) String() string {
	if i >= LogLevel(len(_LogLevel_index)-1) {
		return fmt.Sprintf("LogLevel(%d)", i)
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
