#!/bin/bash

set -e

NAME=smb
USER=rclone
PASS=GNF3Cqeu
WORKGROUP=thepub

. $(dirname "$0")/docker.bash

start() {
    docker run --rm -d --name $NAME dperson/samba \
           -p \
           -u "rclone;${PASS}" \
           -w "${WORKGROUP}" \
           -s "public;/share" \
           -s "rclone;/rclone;yes;no;no;rclone"
    
    echo type=smb
    echo host=$(docker_ip)
    echo user=$USER
    echo pass=$(rclone obscure $PASS)
    echo domain=$WORKGROUP
    echo _connect=$(docker_ip):139
}

. $(dirname "$0")/run.bash
