#!/usr/bin/env bash

set -e

NAME=swift-aio
PORT=28628

. $(dirname "$0")/docker.bash

start() {
    docker run --rm -d --name ${NAME} \
           -p 127.0.0.1:${PORT}:8080 \
           bouncestorage/swift-aio
    
    echo type=swift
    echo env_auth=false
    echo user=test:tester
    echo key=testing
    echo auth=http://127.0.0.1:${PORT}/auth/v1.0
    echo _connect=127.0.0.1:${PORT}
}

. $(dirname "$0")/run.bash
