#!/usr/bin/env bash

set -e

NAME=rclone-serve-sftp
USER=rclone
PASS=CranesBallotDorsey5
IP=127.0.0.1
PORT=28621

start() {
    run rclone serve sftp --user $USER --pass $PASS --addr ${IP}:${PORT} ${DATADIR}
    
    echo type=sftp
    echo host=${IP}
    echo port=$PORT
    echo user=$USER
    echo pass=$(rclone obscure $PASS)
    echo _connect=${IP}:${PORT}
}

. $(dirname "$0")/rclone-serve.bash
