#!/bin/bash

set -e

NAME=rclone-sftp-openssh
USER=rclone
PASS=password

. $(dirname "$0")/docker.bash

start() {
    docker run --rm -d --name ${NAME} \
           rclone/test-sftp-openssh
    
    echo type=sftp
    echo host=$(docker_ip)
    echo user=$USER
    echo pass=$(rclone obscure $PASS)
    echo _connect=$(docker_ip):22
}

. $(dirname "$0")/run.bash
