{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/source.full_control": {
          "description": "Manage your source code repositories"
        },
        "https://www.googleapis.com/auth/source.read_only": {
          "description": "View the contents of your source code repositories"
        },
        "https://www.googleapis.com/auth/source.read_write": {
          "description": "Manage the contents of your source code repositories"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://sourcerepo.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Cloud Source Repositories",
  "description": "Access source code repositories hosted by Google.",
  "discoveryVersion": "v1",
  "documentationLink": "https://cloud.google.com/source-repositories/docs/apis",
  "id": "sourcerepo:v1",
  "kind": "discovery#restDescription",
  "name": "sourcerepo",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "projects": {
      "resources": {
        "repos": {
          "methods": {
            "create": {
              "description": "Creates a repo in the given project with the given name.\n\nIf the named repository already exists, `CreateRepo` returns\n`ALREADY_EXISTS`.",
              "flatPath": "v1/projects/{projectsId}/repos",
              "httpMethod": "POST",
              "id": "sourcerepo.projects.repos.create",
              "path": "v1/{+parent}/repos",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "delete": {
              "description": "Deletes a repo.",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "httpMethod": "DELETE",
              "id": "sourcerepo.projects.repos.delete",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "get": {
              "description": "Returns information about a repo.",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "httpMethod": "GET",
              "id": "sourcerepo.projects.repos.get",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "getIamPolicy": {
              "description": "Gets the access control policy for a resource.\nReturns an empty policy if the resource exists and does not have a policy\nset.",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:getIamPolicy",
              "httpMethod": "GET",
              "id": "sourcerepo.projects.repos.getIamPolicy",
              "path": "v1/{+resource}:getIamPolicy",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "list": {
              "description": "Returns all repos belonging to a project. The sizes of the repos are\nnot set by ListRepos.  To get the size of a repo, use GetRepo.",
              "flatPath": "v1/projects/{projectsId}/repos",
              "httpMethod": "GET",
              "id": "sourcerepo.projects.repos.list",
              "path": "v1/{+name}/repos",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "setIamPolicy": {
              "description": "Sets the access control policy on the specified resource. Replaces any\nexisting policy.",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:setIamPolicy",
              "httpMethod": "POST",
              "id": "sourcerepo.projects.repos.setIamPolicy",
              "path": "v1/{+resource}:setIamPolicy",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "testIamPermissions": {
              "description": "Returns permissions that a caller has on the specified resource.\nIf the resource does not exist, this will return an empty set of\npermissions, not a NOT_FOUND error.",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:testIamPermissions",
              "httpMethod": "POST",
              "id": "sourcerepo.projects.repos.testIamPermissions",
              "path": "v1/{+resource}:testIamPermissions",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            }
          }
        }
      }
    }
  },
  "revision": "20180226",
  "rootUrl": "https://sourcerepo.googleapis.com/",
  "servicePath": "",
  "title": "Cloud Source Repositories API",
  "version": "v1",
  "version_module": true
}