{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive": {
          "description": "View and manage the files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "View metadata for files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "View the files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        }
      }
    }
  },
  "basePath": "/drive/v3/",
  "baseUrl": "https://www.googleapis.com/drive/v3/",
  "batchPath": "batch/drive/v3",
  "description": "Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/drive/",
  "etag": "\"Zkyw9ACJZUvcYmlFaKGChzhmtnE/60h7ViKsodHGCzKStsqADfQgTZ0\"",
  "id": "drive:v3",
  "kind": "discovery#restDescription",
  "name": "drive",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "about": {
      "methods": {
        "get": {
          "description": "Gets information about the user, the user's Drive, and system capabilities.",
          "httpMethod": "GET",
          "id": "drive.about.get",
          "path": "about",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "changes": {
      "methods": {
        "getStartPageToken": {
          "description": "Gets the starting pageToken for listing future changes.",
          "httpMethod": "GET",
          "id": "drive.changes.getStartPageToken",
          "path": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists the changes for a user or Team Drive.",
          "httpMethod": "GET",
          "id": "drive.changes.list",
          "path": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true
        },
        "watch": {
          "description": "Subscribes to changes for a user.",
          "httpMethod": "POST",
          "id": "drive.changes.watch",
          "path": "changes/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "description": "Stop watching resources through this channel",
          "httpMethod": "POST",
          "id": "drive.channels.stop",
          "path": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "comments": {
      "methods": {
        "create": {
          "description": "Creates a new comment on a file.",
          "httpMethod": "POST",
          "id": "drive.comments.create",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "description": "Deletes a comment.",
          "httpMethod": "DELETE",
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a comment by ID.",
          "httpMethod": "GET",
          "id": "drive.comments.get",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists a file's comments.",
          "httpMethod": "GET",
          "id": "drive.comments.list",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a comment with patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.comments.update",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "copy": {
          "description": "Creates a copy of a file and applies any requested updates with patch semantics.",
          "httpMethod": "POST",
          "id": "drive.files.copy",
          "path": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ]
        },
        "create": {
          "description": "Creates a new file.",
          "httpMethod": "POST",
          "id": "drive.files.create",
          "path": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "supportsMediaUpload": true,
          "supportsSubscription": true
        },
        "delete": {
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a Team Drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.",
          "httpMethod": "DELETE",
          "id": "drive.files.delete",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "emptyTrash": {
          "description": "Permanently deletes all of the user's trashed files.",
          "httpMethod": "DELETE",
          "id": "drive.files.emptyTrash",
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "export": {
          "description": "Exports a Google Doc to the requested MIME type and returns the exported content. Please note that the exported content is limited to 10MB.",
          "httpMethod": "GET",
          "id": "drive.files.export",
          "path": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true
        },
        "generateIds": {
          "description": "Generates a set of file IDs which can be provided in create requests.",
          "httpMethod": "GET",
          "id": "drive.files.generateIds",
          "path": "files/generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a file's metadata or content by ID.",
          "httpMethod": "GET",
          "id": "drive.files.get",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "useMediaDownloadService": true
        },
        "list": {
          "description": "Lists or searches files.",
          "httpMethod": "GET",
          "id": "drive.files.list",
          "path": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a file's metadata and/or content with patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.files.update",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "supportsMediaUpload": true
        },
        "watch": {
          "description": "Subscribes to changes to a file",
          "httpMethod": "POST",
          "id": "drive.files.watch",
          "path": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "useMediaDownloadService": true
        }
      }
    },
    "permissions": {
      "methods": {
        "create": {
          "description": "Creates a permission for a file or Team Drive.",
          "httpMethod": "POST",
          "id": "drive.permissions.create",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "description": "Deletes a permission.",
          "httpMethod": "DELETE",
          "id": "drive.permissions.delete",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a permission by ID.",
          "httpMethod": "GET",
          "id": "drive.permissions.get",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists a file's or Team Drive's permissions.",
          "httpMethod": "GET",
          "id": "drive.permissions.list",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a permission with patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.permissions.update",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "replies": {
      "methods": {
        "create": {
          "description": "Creates a new reply to a comment.",
          "httpMethod": "POST",
          "id": "drive.replies.create",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "description": "Deletes a reply.",
          "httpMethod": "DELETE",
          "id": "drive.replies.delete",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a reply by ID.",
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists a comment's replies.",
          "httpMethod": "GET",
          "id": "drive.replies.list",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a reply with patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.replies.update",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "delete": {
          "description": "Permanently deletes a revision. This method is only applicable to files with binary content in Drive.",
          "httpMethod": "DELETE",
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a revision's metadata or content by ID.",
          "httpMethod": "GET",
          "id": "drive.revisions.get",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": true
        },
        "list": {
          "description": "Lists a file's revisions.",
          "httpMethod": "GET",
          "id": "drive.revisions.list",
          "path": "files/{fileId}/revisions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a revision with patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.revisions.update",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "create": {
          "description": "Creates a new Team Drive.",
          "httpMethod": "POST",
          "id": "drive.teamdrives.create",
          "path": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "description": "Permanently deletes a Team Drive for which the user is an organizer. The Team Drive cannot contain any untrashed items.",
          "httpMethod": "DELETE",
          "id": "drive.teamdrives.delete",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "description": "Gets a Team Drive's metadata by ID.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.get",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists the user's Team Drives.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "path": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a Team Drive's metadata",
          "httpMethod": "PATCH",
          "id": "drive.teamdrives.update",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    }
  },
  "revision": "20180413",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "drive/v3/",
  "title": "Drive API",
  "version": "v3"
}