// Code generated by "stringer -type=vState"; DO NOT EDIT.

package vfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[vOK-0]
	_ = x[vAddFile-1]
	_ = x[vDelFile-2]
	_ = x[vAddDir-3]
	_ = x[vDelDir-4]
}

const _vState_name = "vOKvAddFilevDelFilevAddDirvDelDir"

var _vState_index = [...]uint8{0, 3, 11, 19, 26, 33}

func (i vState) String() string {
	if i >= vState(len(_vState_index)-1) {
		return "vState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _vState_name[_vState_index[i]:_vState_index[i+1]]
}
