//go:build windows
// +build windows

// Code generated by "stringer -type=rdnAttrType"; DO NOT EDIT.

package wincrypt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMONNAME-0]
	_ = x[SERIALNUMBER-1]
	_ = x[COUNTRYNAME-2]
	_ = x[LOCALITYNAME-3]
	_ = x[STATEORPROVINCENAME-4]
	_ = x[STREETADDRESS-5]
	_ = x[ORGANIZATIONNAME-6]
	_ = x[ORGANIZATIONALUNITNAME-7]
	_ = x[POSTALCODE-8]
	_ = x[ATTRUNSPECIFIED-9]
}

const _rdnAttrType_name = "COMMONNAMESERIALNUMBERCOUNTRYNAMELOCALITYNAMESTATEORPROVINCENAMESTREETADDRESSORGANIZATIONNAMEORGANIZATIONALUNITNAMEPOSTALCODEATTRUNSPECIFIED"

var _rdnAttrType_index = [...]uint8{0, 10, 22, 33, 45, 64, 77, 93, 115, 125, 140}

func (i rdnAttrType) String() string {
	if i < 0 || i >= rdnAttrType(len(_rdnAttrType_index)-1) {
		return "rdnAttrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _rdnAttrType_name[_rdnAttrType_index[i]:_rdnAttrType_index[i+1]]
}
