{
  "revision": "20170704",
  "documentationLink": "https://developers.google.com/people/",
  "id": "people:v1",
  "discoveryVersion": "v1",
  "version_module": "True",
  "protocol": "rest",
  "canonicalName": "People Service",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/plus.login": {
          "description": "Know the list of people in your circles, your age range, and language"
        },
        "https://www.googleapis.com/auth/userinfo.profile": {
          "description": "View your basic profile info"
        },
        "https://www.googleapis.com/auth/user.emails.read": {
          "description": "View your email addresses"
        },
        "https://www.googleapis.com/auth/contacts": {
          "description": "Manage your contacts"
        },
        "https://www.googleapis.com/auth/user.addresses.read": {
          "description": "View your street addresses"
        },
        "https://www.googleapis.com/auth/user.phonenumbers.read": {
          "description": "View your phone numbers"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.googleapis.com/auth/contacts.readonly": {
          "description": "View your contacts"
        },
        "https://www.googleapis.com/auth/user.birthday.read": {
          "description": "View your complete date of birth"
        }
      }
    }
  },
  "rootUrl": "https://people.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "people",
  "batchPath": "batch",
  "title": "Google People API",
  "ownerName": "Google",
  "resources": {
    "contactGroups": {
      "methods": {
        "batchGet": {
          "path": "v1/contactGroups:batchGet",
          "id": "people.contactGroups.batchGet",
          "description": "Get a list of contact groups owned by the authenticated user by specifying\na list of contact group resource names.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "flatPath": "v1/contactGroups:batchGet"
        },
        "delete": {
          "description": "Delete an existing contact group owned by the authenticated user by\nspecifying a contact group resource name.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "id": "people.contactGroups.delete",
          "path": "v1/{+resourceName}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "flatPath": "v1/contactGroups",
          "path": "v1/contactGroups",
          "id": "people.contactGroups.list",
          "description": "List all contact groups owned by the authenticated user. Members of the\ncontact groups are not populated."
        },
        "create": {
          "description": "Create a new contact group owned by the authenticated user.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups",
          "id": "people.contactGroups.create",
          "path": "v1/contactGroups"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "id": "people.contactGroups.get",
          "path": "v1/{+resourceName}",
          "description": "Get a specific contact group owned by the authenticated user by specifying\na contact group resource name."
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "path": "v1/{+resourceName}",
          "id": "people.contactGroups.update",
          "description": "Update the name of an existing contact group owned by the authenticated\nuser."
        }
      },
      "resources": {
        "members": {
          "methods": {
            "modify": {
              "description": "Modify the members of a contact group owned by the authenticated user.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/contacts"
              ],
              "flatPath": "v1/contactGroups/{contactGroupsId}/members:modify",
              "id": "people.contactGroups.members.modify",
              "path": "v1/{+resourceName}/members:modify"
            }
          }
        }
      }
    },
    "people": {
      "methods": {
        "getBatchGet": {
          "path": "v1/people:batchGet",
          "id": "people.people.getBatchGet",
          "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.\n\u003cbr\u003e\nThe request throws a 400 error if 'personFields' is not specified.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "flatPath": "v1/people:batchGet"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "flatPath": "v1/people/{peopleId}",
          "path": "v1/{+resourceName}",
          "id": "people.people.get",
          "description": "Provides information about a person by specifying a resource name. Use\n`people/me` to indicate the authenticated user.\n\u003cbr\u003e\nThe request throws a 400 error if 'personFields' is not specified."
        },
        "updateContact": {
          "flatPath": "v1/people/{peopleId}:updateContact",
          "id": "people.people.updateContact",
          "path": "v1/{+resourceName}:updateContact",
          "description": "Update contact data for an existing contact person. Any non-contact data\nwill not be modified.\n\nThe request throws a 400 error if `updatePersonFields` is not specified.\n\u003cbr\u003e\nThe request throws a 400 error if `person.metadata.sources` is not\nspecified for the contact to be updated.\n\u003cbr\u003e\nThe request throws a 412 error if `person.metadata.sources.etag` is\ndifferent than the contact's etag, which indicates the contact has changed\nsince its data[...]",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        },
        "createContact": {
          "id": "people.people.createContact",
          "path": "v1/people:createContact",
          "description": "Create a new contact and return the person resource for that contact.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/people:createContact"
        },
        "deleteContact": {
          "flatPath": "v1/people/{peopleId}:deleteContact",
          "id": "people.people.deleteContact",
          "path": "v1/{+resourceName}:deleteContact",
          "description": "Delete a contact person. Any non-contact data will not be deleted.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        }
      },
      "resources": {
        "connections": {
          "methods": {
            "list": {
              "flatPath": "v1/people/{peopleId}/connections",
              "id": "people.people.connections.list",
              "path": "v1/{+resourceName}/connections",
              "description": "Provides a list of the authenticated user's contacts merged with any\nconnected profiles.\n\u003cbr\u003e\nThe request throws a 400 error if 'personFields' is not specified.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/contacts",
                "https://www.googleapis.com/auth/contacts.readonly"
              ]
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://people.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "Provides access to information about profiles and contacts.",
  "servicePath": "",
  "basePath": ""
}
